general {
  after_sleep_cmd=hyprctl dispatch dpms on
  before_sleep_cmd=loginctl lock-session
  ignore_dbus_inhibit=false
  lock_cmd=lockscreen
}

listener {
  on-resume=brightnessctl -r
  on-timeout=brightnessctl -e4 -s set 25%
  timeout=300
}

listener {
  on-timeout=loginctl lock-session
  timeout=1200
}

listener {
  on-resume=hyprctl dispatch dpms on
  on-timeout=hyprctl dispatch dpms off
  timeout=1350
}
